set column_ratios 0,2,3
set show_hidden true
set preview_images true
set preview_images_method ueberzug
default_linemode devicons

# Archives
map ex extract
map ec compress

# Move to Trash
map DD shell mv %s /home/${USER}/.local/share/Trash/files/
