-- Init.lua --
require("themes/feather-darker")
require("plugins")
require("settings")
require("keymaps")
require("lua-devicons")
require("lua-bufferline")
require("lua-lualine")
require("lua-gitsigns")
require("lua-lsp")
require("lua-lspCompe")
require("lua-nvimTree")
require("lua-telescope")
require("lua-treesitter")
require("lua-colorizer")
require("nvim-autopairs").setup()

