-- Init.lua --
require("plugins")
require("settings")
require("keymaps")
require("lua-devicons")
require("lua-bufferline")
require("lua-galaxyline")
require("lua-gitsigns")
require("lua-lsp")
require("lua-lspCompe")
require("lua-nvimTree")
require("lua-telescope")
require("lua-treesitter")
require("colorizer").setup()
require("nvim-autopairs").setup()
require("themes/plunne-darker")
